[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "./x86_64-takos.json"

[target.'cfg(target_os = "none")']
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "relocation-model=static", "-C", "code-model=kernel"]
runner = "../runner.fish"