use super::keycodes::KeyCode;

pub fn layout_lower_case(key_code: KeyCode) -> Option<char> {
    Some(match key_code {
        KeyCode::Number1 | KeyCode::NumPad1 => '1',
        KeyCode::Number2 | KeyCode::NumPad2 => '2',
        KeyCode::Number3 | KeyCode::NumPad3 => '3',
        KeyCode::Number4 | KeyCode::NumPad4 => '4',
        KeyCode::Number5 | KeyCode::NumPad5 => '5',
        KeyCode::Number6 | KeyCode::NumPad6 => '6',
        KeyCode::Number7 | KeyCode::NumPad7 => '7',
        KeyCode::Number8 | KeyCode::NumPad8 => '8',
        KeyCode::Number9 | KeyCode::NumPad9 => '9',
        KeyCode::Number0 | KeyCode::NumPad0 => '0',
        KeyCode::Minus | KeyCode::NumPadSub => '-',
        KeyCode::Equals => '=',
        KeyCode::BackSlash => '\\',
        KeyCode::Slash | KeyCode::NumPadDiv => '/',
        KeyCode::NumPadAdd => '+',
        KeyCode::NumPadMul => '*',
        KeyCode::Tab => '\t',
        KeyCode::LeftBracket => '[',
        KeyCode::RightBracket => ']',
        KeyCode::Enter | KeyCode::NumPadEnter => '\n',
        KeyCode::Semicolon => ';',
        KeyCode::Apostrophe => '\'',
        KeyCode::Comma => ',',
        KeyCode::Period | KeyCode::NumPadPeriod => '.',
        KeyCode::Space => ' ',

        KeyCode::Q => 'q',
        KeyCode::W => 'w',
        KeyCode::E => 'e',
        KeyCode::R => 'r',
        KeyCode::T => 't',
        KeyCode::Y => 'y',
        KeyCode::U => 'u',
        KeyCode::I => 'i',
        KeyCode::O => 'o',
        KeyCode::P => 'p',
        KeyCode::A => 'a',
        KeyCode::S => 's',
        KeyCode::D => 'd',
        KeyCode::F => 'f',
        KeyCode::G => 'g',
        KeyCode::H => 'h',
        KeyCode::J => 'j',
        KeyCode::K => 'k',
        KeyCode::L => 'l',
        KeyCode::Z => 'z',
        KeyCode::X => 'x',
        KeyCode::C => 'c',
        KeyCode::V => 'v',
        KeyCode::B => 'b',
        KeyCode::N => 'n',
        KeyCode::M => 'm',

        _ => return None,
    })
}

pub fn layout_upper_case(key_code: KeyCode) -> Option<char> {
    Some(match key_code {
        KeyCode::Number1 => '!',
        KeyCode::Number2 => '@',
        KeyCode::Number3 => '#',
        KeyCode::Number4 => '$',
        KeyCode::Number5 => '%',
        KeyCode::Number6 => '^',
        KeyCode::Number7 => '&',
        KeyCode::Number8 | KeyCode::NumPadMul => '*',
        KeyCode::Number9 => '(',
        KeyCode::Number0 => ')',

        KeyCode::NumPad1 => '1',
        KeyCode::NumPad2 => '2',
        KeyCode::NumPad3 => '3',
        KeyCode::NumPad4 => '4',
        KeyCode::NumPad5 => '5',
        KeyCode::NumPad6 => '6',
        KeyCode::NumPad7 => '7',
        KeyCode::NumPad8 => '8',
        KeyCode::NumPad9 => '9',
        KeyCode::NumPad0 => '0',

        KeyCode::Minus => '_',
        KeyCode::NumPadSub => '-',
        KeyCode::Equals | KeyCode::NumPadAdd => '+',
        KeyCode::BackSlash => '|',
        KeyCode::Slash => '?',
        KeyCode::NumPadDiv => '/',

        KeyCode::Tab => '\t',
        KeyCode::LeftBracket => '{',
        KeyCode::RightBracket => '}',
        KeyCode::Enter | KeyCode::NumPadEnter => '\n',
        KeyCode::Semicolon => ':',
        KeyCode::Apostrophe => '"',
        KeyCode::Comma => '<',
        KeyCode::Period => '>',
        KeyCode::NumPadPeriod => '.',
        KeyCode::Space => ' ',

        KeyCode::Q => 'Q',
        KeyCode::W => 'W',
        KeyCode::E => 'E',
        KeyCode::R => 'R',
        KeyCode::T => 'T',
        KeyCode::Y => 'Y',
        KeyCode::U => 'U',
        KeyCode::I => 'I',
        KeyCode::O => 'O',
        KeyCode::P => 'P',
        KeyCode::A => 'A',
        KeyCode::S => 'S',
        KeyCode::D => 'D',
        KeyCode::F => 'F',
        KeyCode::G => 'G',
        KeyCode::H => 'H',
        KeyCode::J => 'J',
        KeyCode::K => 'K',
        KeyCode::L => 'L',
        KeyCode::Z => 'Z',
        KeyCode::X => 'X',
        KeyCode::C => 'C',
        KeyCode::V => 'V',
        KeyCode::B => 'B',
        KeyCode::N => 'N',
        KeyCode::M => 'M',

        _ => return None,
    })
}